### ISSUE TITLE
Should this line not be explaining the opposite?

### ISSUE THREAD

**Issue by danwdart** [cdsmith/explainable-predicates#10]
https://github.com/cdsmith/explainable-predicates/blob/3b4f5df776d5dd8238e6aecd0ade69a40fe5ffb2/src/Test/Predicates.hs#L483

**Comment by cdsmith** [comment]
Explanations are statements of a fact that justifies the decision about whether a predicate applies or not.  For example, if the predicate is `containsAll [eq 1, eq 2, eq 3]`, then a good explanation would be "The value doesn't contain 3".  This statement is a good justification, regardless of whether you're trying to explain why `containsAll [eq 1, eq 2, eq 3]` accepts, or why `notP (containsAll [eq 1, eq 2, eq 3])` rejects.

**Comment by danwdart** [comment]
Ah, fair enough.
