### ISSUE TITLE
Algebraic manipulation of predicates

### ISSUE THREAD

**Issue by ocramz** [cdsmith/explainable-predicates#13]
There should be a way to combine predicates e.g. by leveraging the fact that (a -> Bool) is an instance of a Lattice (https://hackage.haskell.org/package/lattices-2.0.2/docs/Algebra-Lattice.html#t:Lattice)

**Comment by cdsmith** [comment]
I'm not 100% sure I understand what you mean here.  `andP` and `orP` are already there, and I believe those are the lattice operations you're looking for.  Is this a request for a `Lattice` instance?

**Comment by ocramz** [comment]
I now realize `lattices` would add a large dependency burden which you perhaps were seeking to avoid.
