### ISSUE TITLE
GHC 9.2.1 support

### ISSUE THREAD

**Issue by TravisCardwell** [cdsmith/explainable-predicates#14]
I am using HMock and `explainable-predicates` with GHC 9.2.1 without issue, using `allow-newer` configuration to ignore the upper bound constraints on the `base` and `template-haskell` dependencies.  I investigated bumping these constraints so that the next releases will work without the `allow-newer` configuration.

The `explainable-predicates` tests all pass with GHC 9.2.1 with the following changes:

```diff
diff --git a/explainable-predicates.cabal b/explainable-predicates.cabal
index 1861e7a..9adc77b 100644
--- a/explainable-predicates.cabal
+++ b/explainable-predicates.cabal
@@ -56,9 +56,9 @@ library
                          Test.Predicates.Internal.FlowMatcher
     other-modules:       Test.Predicates.Internal.Util
     build-depends:       array >= 0.5.2 && < 0.6,
-                         base >=4.12.0 && < 4.16,
+                         base >=4.12.0 && < 4.17,
                          syb >= 0.7.2 && < 0.8,
-                         template-haskell >= 2.13.0 && < 2.18,
+                         template-haskell >= 2.13.0 && < 2.19,
     hs-source-dirs:      src
     default-language:    Haskell2010
     ghc-options:         -Wall -Wcompat -Wincomplete-uni-patterns
```

The following changes also need to be made:

- [ ] `.travis.yml` - Update `ghc`
- [ ] `explainable-predicates.cabal` - Update `tested-with`
- [ ] `README.md` - Update "Which GHC versions are supported?"
- [ ] `CHANGELOG.md` - Add entry?

**Comment by cdsmith** [comment]
I've released a new version that fixes this.
