### ISSUE TITLE
Add an infix operator for accept

### ISSUE THREAD

**Issue by cdsmith** [cdsmith/explainable-predicates#6]
An infix operator for `accept` would be nice.  I'm not sure which one it should be.  `=~` has been suggested, but we should briefly look for other widespread uses first.

**Comment by stuebinm** [comment]
`=~` is currently used for matching regular expressions (cf. [regex-base](https://hackage.haskell.org/package/regex-base-0.94.0.1/docs/Text-Regex-Base.html)).

Though I haven't yet played around with `explainable-predicates`, I've been thinking it could fit into a linter I'm writing (which essentially type-checks asset files of a game, and should emit hints if things go wrong), which also uses regular expressions, i.e. these would collide (I could also imagine people using regexes in tests, e.g. to check program output or a pretty-printer). That's obviously not a dealbreaker or anything, but it would be nice if it were avoided.

**Comment by cdsmith** [comment]
Agreed.  I don't have a strong opinion here.  Hoogle says that `==~` is unused in Stackage.
