### ISSUE TITLE
Cabal flags for heavyweight dependencies

### ISSUE THREAD

**Issue by cdsmith** [cdsmith/explainable-predicates#7]
explainable-predicates has a few very heavyweight dependencies: `mono-traversable`, and `regex-tdfa`.  We could offer cabal flags to disable those predicates if someone knows they won't be using them.  This would also provide a story for adding more heavy dependencies in the future, such as an XML library for XML-based predicates, while not adversely affecting people who care about keeping their deps slim.

**Comment by brandonchinn178** [comment]
@cdsmith thoughts on making these flags default to false?

**Comment by cdsmith** [comment]
I think I prefer to leave the flags true by default.  That way everything works by default even if it's a but slower, and if you go out of your way to remove some functionality, you probably know that you have done so.  The other default has a worse failure case where sample code using explainable-predicates may fail on your system because you haven't overridden a flag.
