### ISSUE TITLE
QuickCheck integration

### ISSUE THREAD

**Issue by Bodigrim** [cdsmith/explainable-predicates#8]
It would be handy to have 

```haskell
toProperty :: Predicate t -> t -> Test.QuickCheck.Property
toProperty p t = counterexample (explain p t) (accept p t)
```

Then `toProperty p` becomes an instance of `Test.QuickCheck.Testable` with all nice implications of it.

----

I wonder whether a deeper integration might be desirable/possible, e. g.,

```haskell
newtype Predicate t = Predicate (t -> Test.QuickCheck.Property) 
```

**Comment by brandonchinn178** [comment]
Related: https://github.com/nick8325/quickcheck/issues/334
